# Generated by Django 3.2.2 on 2021-05-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PreprintDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(blank=True, max_length=40, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='media')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('public_data_link', models.CharField(blank=True, max_length=50, null=True)),
                ('public_data_not_available_describe', models.TextField(blank=True, null=True)),
                ('type_available_link', models.CharField(blank=True, max_length=30, null=True)),
                ('type_available_link_type', models.CharField(blank=True, max_length=40, null=True)),
                ('type_not_availabe_description', models.TextField(blank=True, null=True)),
                ('license_type', models.CharField(blank=True, max_length=40, null=True)),
                ('year', models.CharField(blank=True, max_length=30, null=True)),
                ('copyright_holder', models.CharField(blank=True, max_length=30, null=True)),
                ('doi', models.CharField(blank=True, max_length=30, null=True)),
                ('pubdate', models.CharField(blank=True, max_length=12, null=True)),
                ('keywords', models.CharField(blank=True, max_length=50, null=True)),
                ('absctract', models.TextField(blank=True, null=True)),
                ('selected_main_taxonomy', models.CharField(blank=True, max_length=40, null=True)),
                ('selected_texonomy', models.CharField(blank=True, max_length=30, null=True)),
                ('authors', models.CharField(blank=True, max_length=60, null=True)),
                ('conflict_interest_describe', models.TextField(blank=True, null=True)),
                ('default_author', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
