# Generated by Django 3.2.2 on 2021-05-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_preprintdetails_default_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preprintdetails',
            options={'verbose_name': 'preprint details', 'verbose_name_plural': 'preprint details'},
        ),
        migrations.AddField(
            model_name='preprintdetails',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
