# Generated by Django 3.2.2 on 2021-05-26 05:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_preprintdetails_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='preprintdetails',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
