# Generated by Django 3.2.2 on 2021-05-26 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_preprintdetails_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preprintdetails',
            name='copyright_holder',
            field=models.CharField(blank=True, max_length=110, null=True),
        ),
        migrations.AlterField(
            model_name='preprintdetails',
            name='keywords',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='preprintdetails',
            name='selected_main_taxonomy',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='preprintdetails',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
