# Generated by Django 3.2.2 on 2021-05-26 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20210526_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preprintdetails',
            name='selected_texonomy',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
