# Generated by Django 3.2.2 on 2021-05-27 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_preprintdetails_selected_texonomy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Downloads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField(default=0)),
                ('preprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.preprintdetails')),
            ],
        ),
    ]
