# Generated by Django 3.2.2 on 2021-05-27 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_downloads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloads',
            name='preprint',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.preprintdetails'),
        ),
    ]
